---
cloud1_project_dir: /opt/cloud1
cloud1_domain: cloud-1.fun
cloud1_wordpress_domain: cloud-1.fun
  #cloud1_domain: mywp-cloud1.duckdns.org

  # Pour le script
cloud1_letsencrypt_email: agonelle.mobile@gmail.com
cloud1_letsencrypt_use_staging: true
cloud1_letsencrypt_force: false
cloud1_project_name: "{{ cloud1_project_dir | basename }}"

cloud1_letsencrypt_cert_path: "{{ cloud1_project_dir }}/data/certs/live/{{ cloud1_domain }}/fullchain.pem"


cloud1_mysql_root_password: "super_password"
cloud1_mysql_password: "super_password_mysql"
