$ANSIBLE_VAULT;1.1;AES256
36353937313532616361336633643962363264303131613637303534373133346435653639633236
6264356662383336633263643165356233303866383037390a393233383962636562393938333266
31373037643662386531656335393962383566346138613438653531366661373236313138373362
3261613730656239370a613235303562323766316436376661336531663934336634303462616134
31373066613035313337396532373161383361663530656538303962626136633732393136616638
63653239336565303333656438616537373034373464373830613961356562333566653961666465
36646531383437303164613964636537313864353730626238616664633964653938633061386137
62623336373064303236333161663538656231383936636530643332616561343464396463633633
65636265373330656535313364336630393930376665373330353964623830633936336161326631
37363038616462626535353136613735626137633134306131633764313635333461376531353464
66633566313632316232343364623035613132303734333338303466396336643334643036343363
34343732343930636337356530666436353366636662316138333935643564623162656534653263
36626636646461346364303038336462653262393463386661326635663435333666353165646130
37653133336661613865613862653562303332313738356237303435646563343035653839353633
656265376430303737633161383231373965
