---
- name: Configuration des serveurs WordPress
  hosts: wordpress_servers
  gather_facts: yes
  become: true
  roles:
    - role: docker_server
      tags: [docker, setup]
    - role: cloud-1
      tags: [app, deploy]
    - role: letsencrypt_manager
      tags: [ssl, certs]
