---
cloud1_domain: cloud-1.fun
cloud1_wordpress_domain: cloud-1.fun
#cloud1_domain: mywp-cloud1.duckdns.org

# Pour le script
cloud1_letsencrypt_email: agonelle.mobile@gmail.com
cloud1_letsencrypt_use_staging: true
cloud1_letsencrypt_force: false


cloud1_mysql_root_password: "{{ vault_cloud1_mysql_root_password }}"
cloud1_mysql_password: "{{ vault_cloud1_mysql_password }}"
