$ANSIBLE_VAULT;1.1;AES256
32373762623836346661633337356430353062303434363235616164366230363763343661656339
3764333633376236636639303662396462643734363539340a306366623038393161326566653561
33656132626361333563666135366466633930356234306136316661623861643565313331386465
6231663766393963350a343339373931353631643463326236353962393335353836666132306535
30383963316137646165323235333737323230363835386334636463663164363336613934663937
35353664353336616634633563653566336165363066393234356638636631313339393061633839
30363035356432343265616630303462363766613736323332346135613136646462666237326363
36356531383863303061323336333463313731383561373339313436363365626335616537656635
38303838636338323165303864333133346561393030623364326662353063353831
